### ISSUE TITLE
Issue on page /01-Introduction-To-Causality.html

### ISSUE THREAD

**Issue by joaopcnogueira** [matheusfacure/python-causality-handbook#10]
Hi Matheus, thank you very much for the hard work you have put into this book! I am just at the beginning and I already learned a lot.

I think there is a typo problem on the math of ATE shown on the figure below, as it should be 125.

![image](https://user-images.githubusercontent.com/17098391/99961766-bf5a8d80-2d6d-11eb-817b-49cdd1de7bcd.png)

**Comment by matheusfacure** [comment]
Nice catch! Fixed it.
