### ISSUE TITLE
Clarifications on Chapter 4

### ISSUE THREAD

**Issue by y1-y0** [matheusfacure/python-causality-handbook#107]
I would appreciate if you could clarify the following:

1. Is any indirect path between T and Y - backdoor path?

2. 
>  A path is blocked if and only if:
> It contains a non collider that has been conditioned on

Could you please clarify why did you use "non collider" instead of simply "confounder"? Non colliders are either confounders or mediators. But conditioning on mediator results in the selection bias. So that leaves us with confounders.

Thank you!

**Comment by matheusfacure** [comment]
Hey, sure! Can you check answer 6. in the example afterwards? It provides an example of a non collider that it's not a confounder. 
Cool name, btw.

**Comment by y1-y0** [comment]
I don't see why it is not a confounder because

<- C ->

Or is there an additional requirement for a node like C to become a confounder?

The name was inspired by your book. I'm really enjoying its conversational style!

**Comment by matheusfacure** [comment]
A confounder is a common cause between the outcome node and the treated node. In this case, let's say A is the treatment and F is the control. C causes A, but not F. 
![image](https://user-images.githubusercontent.com/18542597/125439839-a22c51d9-911f-447a-9b2a-176f663eb67b.png)

**Comment by y1-y0** [comment]
It doesn't cause F because of arrow "E <- F", right? It stops causal flow at E.

In other words, if we rotate that arrow to become "E -> F", then C will become a confounder.

**Comment by matheusfacure** [comment]
The original question goes like this
![image](https://user-images.githubusercontent.com/18542597/126316165-26d06ea0-4206-43b3-9a39-34f844f07846.png)
So, if we condition on E, the path between F  and C is open.

**Comment by y1-y0** [comment]
I think I figured this out. Thank you for clarification!
