### ISSUE TITLE
Typo in Chapter 5

### ISSUE THREAD

**Issue by aliscrodrigues** [matheusfacure/python-causality-handbook#108]
There is an issue on chapter 5, in the following paragraph

This coefficient we’ve just estimated tells us that, for people with the same IQ, experience, tenure, age and so on, we should expect an additional year of education to be associated with a 4.11% increase in hourly wage. This confirms our suspicion that the first simple model with only educ was **biases**

It should be
This coefficient we’ve just estimated tells us that, for people with the same IQ, experience, tenure, age and so on, we should expect an additional year of education to be associated with a 4.11% increase in hourly wage. This confirms our suspicion that the first simple model with only educ was **biased**

**Comment by matheusfacure** [comment]
Thanks for the feedback. It should be fixed by the next release.
