### ISSUE TITLE
is there chinese version?

### ISSUE THREAD

**Issue by xuningwang** [matheusfacure/python-causality-handbook#109]
hey there,

i am a student from China, i wonder is there Chinese version for this wonderful book? or if there any translation project for this book.

thx in advance.

**Comment by xuningwang** [comment]
if any translation project, i would like to offer some effort.

**Comment by matheusfacure** [comment]
Hey @xuningwang, currently no. We only have a Vietnamese version https://github.com/vietecon/NhanQuaPython.
 
I also have some plans of translating it to Portuguese, but currently, all my efforts are in writing part two of the book. 
 
I sadly don't speak Chinese, so I would have to count on help from others or pay a translator. The book has only a modest fund on Patreon and I was saving it to pay a english reviewer. As english is not my primary language, there are probably multiple improvements that can be made here.

**Comment by xuningwang** [comment]
> Hey @xuningwang, currently no. We only have a Vietnamese version https://github.com/vietecon/NhanQuaPython.
> 
> I also have some plans of translating it to Portuguese, but currently, all my efforts are in writing part two of the book.
> 
> I sadly don't speak Chinese, so I would have to count on help from others or pay a translator. The book has only a modest fund on Patreon and I was saving it to pay a english reviewer. As english is not my primary language, there are probably multiple improvements that can be made here.

oh i see, anyway thanks for your great work. I learned a lot from this book.
