### ISSUE TITLE
Typo on page /14-Difference-in-Difference.html

### ISSUE THREAD

**Issue by millengustavo** [matheusfacure/python-causality-handbook#112]
We’ve explored a technique widely applied when we are estimating causal effects at more macro entities (schools, cities, states, countries…). Difference in Difference takes a treated unit before and after the treatment and compares the trend in the outcome to that of a control unit. Here, we’ve seen how this could be applied at estimating the effect of a city specific marketing **camping**.

It should be:

We’ve explored a technique widely applied when we are estimating causal effects at more macro entities (schools, cities, states, countries…). Difference in Difference takes a treated unit before and after the treatment and compares the trend in the outcome to that of a control unit. Here, we’ve seen how this could be applied at estimating the effect of a city specific marketing campaign.

**Comment by matheusfacure** [comment]
Thanks for the kind feedback. The fixes should be reflected on the next release.
