### ISSUE TITLE
Issue on page /03-Stats-Review-The-Most-Dangerous-Equation.html

### ISSUE THREAD

**Issue by dlotter** [matheusfacure/python-causality-handbook#114]
It seems that for some reason one of the graphics at chapter 3 doesn't show the labels (at least for me). 

![image](https://user-images.githubusercontent.com/49592361/126404117-976486dd-0fbb-4316-937c-80439a8ac187.png)

Adding `plt.legend()` before `plt.show()` seems to fix the issue for me.

![image](https://user-images.githubusercontent.com/49592361/126405278-bcaf7ae9-872b-41d6-a856-4f18bd01dbd5.png)

**Comment by matheusfacure** [comment]
Thanks for the kind feedback. This fix will be reflected on the next release.
