### ISSUE TITLE
Issue on page /13-Panel-Data-and-Fixed-Effects.html

### ISSUE THREAD

**Issue by ieipi** [matheusfacure/python-causality-handbook#12]
the math formula don't render correctly:

\(\ddot{Y}{it} = Y{it} - \bar{Y}i\)
\(\ddot{X}{it} = X_{it} - \bar{X}_i\)

**Comment by matheusfacure** [comment]
While I don't fix the issue, it looks like the formula renders correctly on Jupyter:
https://github.com/matheusfacure/python-causality-handbook/blob/master/causal-inference-for-the-brave-and-true/13-Panel-Data-and-Fixed-Effects.ipynb
