### ISSUE TITLE
Clarification on 06-Grouped-and-Dummy-Regression.html

### ISSUE THREAD

**Issue by y1-y0** [matheusfacure/python-causality-handbook#122]
I am confused by the plural _parameter**s**_ this sentence:

> If we include more dummy covariates in the model, the parameters on education become a weighted average of the effect on each dummy group

Each parameter is a change relative to the intercept (which is the omitted group). But why do you take the weighted average of them?

Thank you!

**Comment by matheusfacure** [comment]
The plural is wrong. What I meant was that the causal parameter on education will be a weighted average of the causal effect in each group. I'll add a fix.
