### ISSUE TITLE
Issue: Chapter 05-The-Unreasonable-Effectiveness-of-Linear-Regression

### ISSUE THREAD

**Issue by dipetkov** [matheusfacure/python-causality-handbook#126]
In the section "Regression For Non-Random Data", the fitted regression for `log(hourly wage)` is `5.9995 + education * 0.0596`. When the relationship between hourly wage and education is plotted however, the line is `hourly wage = exp(2.2954 + 0.0529 * x)`. The intercept is very different.

Also 25 years of education is a lot of years. I looked at `wage.csv` and in the data education ranges from 9 to 18. Does it make sense to extrapolate outside of this range, as in the statement:
> ... we expect that going from 8 to 9 years of education to be more rewarding than going from 2 to 3 years.

Esp. if going from 2 to 3 years is the difference between being literate or not.

A more interesting comparison might be between 12 years (average to graduate high school) and 16 years (average to graduate college).

**Comment by matheusfacure** [comment]
Nice catch. There was another bug. I was fitting wage instead of hourly wage. Should be fixed soon.
