### ISSUE TITLE
Issue on page /04-Graphical-Causal-Models.html

### ISSUE THREAD

**Issue by laurajchang** [matheusfacure/python-causality-handbook#127]
In the section on confounding bias, for the graph involving X1 and X2, it is stated that Y is independent of T given X1 and X2. Why is it X1 & X2, and not X1 and U?

**Comment by matheusfacure** [comment]
It could be. Y is independent of T given X1 and X2 **OR** given X1 and U. The thing is that you can't condition on U because its unobservable. I'll make that more clear in the chapter.
