### ISSUE TITLE
Issue on page /03-Stats-Review-The-Most-Dangerous-Equation.html

### ISSUE THREAD

**Issue by henrique-cervantes** [matheusfacure/python-causality-handbook#128]
In the first graph of the section "Hypothesis Testing", there might be a typo in its legend:

![image](https://user-images.githubusercontent.com/70850417/131065197-cfe95610-6b92-428f-9682-c04470cb2988.png)

First things first, let's recall that the resulting mean of the difference of two independent normal distributions is equal to the difference of the means of the two distributions:

![image](https://user-images.githubusercontent.com/70850417/131064076-d64e8405-cad6-4362-a74c-00d9307a29d3.png)

Therefore, I believe that instead of N(4,3) - N(1,4) = N(-1, 5), that is, n1 - n2 = n_diff, the result of the difference of the two distributions should be stated in the legend of the graph as n2 - n1 = n_diff, which would then result in N(1,4) - N(4,3) = N(-3, 5).

Indeed, if we run the following code, we'll be able to see that the mean of the resulting distribution is equal to -3:

![image](https://user-images.githubusercontent.com/70850417/131065566-cb1a6716-fc24-4f02-a7c9-1e5d1fb6b370.png)

And thanks a lot for the book, it is truly amazing! ;)

**Comment by matheusfacure** [comment]
Nice catch!
