### ISSUE TITLE
Issue on page 02-Randomised-Experiments.html

### ISSUE THREAD

**Issue by juanbeleno** [matheusfacure/python-causality-handbook#129]
In the section "The Ideal Experiment", probably the term "RCT" means "Randomised controlled trial" (I had to look at Google to find what that term means). However, "Randomised controlled trial" is never mentioned on the page. I think there are two probable solutions:

1) Replace the first appearance of the term "RTC" with "Randomised controlled trial (RTC)" and write a little bit about it and how its meaning is the same than the term you are using: "randomised experiments"

2) Replace "RTC" with "randomised experiments"

**Comment by matheusfacure** [comment]
Good feedback! I'll add those points to the chapter.
