### ISSUE TITLE
Issue on page /20-Plug-and-Play-Estimators.html

### ISSUE THREAD

**Issue by zhenlan0426** [matheusfacure/python-causality-handbook#130]
1. I think this line should be predict_elast(m2, prices_rnd) to make a fair comparison between m1 and m2.

"m1_pred": m2.predict(prices_rnd[X]),

2. predict_elast will be sensitive to the choice of h for tree based model. H too small will land you in a flat region in tree, giving you zero. Too large will not be local change anymore, so not really a derivative. I am not sure what the best choice should be.

3. The elasticity will depend on the number of bands or steps in cumulative_elast_curve. Bands too small, you will not have enough data, hence higher variance. Bands too large, you will be mixing heterogeneous treatment, hence higher bias. Again, I am not sure what the best choice should be L

4. Last but I think the most important one. Why do we care about “slope” more than “level”? I think we should care most about the argmax of the decision variable. Take the ice-cream sales for example. We should care about E[sales(as a function of price) * (price – cost)], where the expectation is taken over sales condition on price and other covariates. The argmax of this objective w.r.t price is what we care about. I think in this case, the level (intercept in regression) also matters. Hence, having an Evaluating metrics that only measures slope does not capture the whole picture in my opinion.

**Comment by matheusfacure** [comment]
2. You are right. The quality of CATE estimates is highly dependent on the ML model
3. Not really, because we are doing cumulative curves, so we have high variance only at the beginning of the curve. 
4. You are sort of right. It is true that we only care about the argmax of the function, but that can be obtained from the derivative alone. Hence, slope (derivative) is what we care about.

**Comment by matheusfacure** [comment]
I'm reopening since I didn't address your 1st point yet.

**Comment by matheusfacure** [comment]
What line are you referring to in point 1?
