### ISSUE TITLE
Issue on page /06-Grouped-and-Dummy-Regression.html

### ISSUE THREAD

**Issue by dipetkov** [matheusfacure/python-causality-handbook#132]
This is not actually a bug but I'm wondering why you implemented it this way.

In ch6, you read the wage data twice.

First:
```
wage = pd.read_csv("./data/wage.csv").dropna()
```
And then:
```
wage = pd.read_csv("./data/wage.csv")
```

Why drop rows with nulls in one case but not the other, even though the `wage`, `educ` and `IQ` variables don't have any nulls? [Most of the rows that do get dropped are for individuals with 12 years of education which seems important.]

**Comment by matheusfacure** [comment]
I think it was a copy paste mistake from previous chapter. No reason to drop na here.
