### ISSUE TITLE
Possible correction on Chapter 2

### ISSUE THREAD

**Issue by lgabs** [matheusfacure/python-causality-handbook#133]
Hi Matheus! I just wanna say that you're doing a beautiful contribution to the society with your book, it's funny and objective, straight to important topics on causality and with some code to follow along! I'm still at the very top of this iceberg, but I'm already enjoying it a lot. Congratulations for this initiative :rocket: 

So for far I have a small question about Chapter 2: shouldn't this phrase be 

> [...] If the _potential_ outcome is independent of the treatment, doesn’t this also imply that the treatment has no effect? [...]

rather than
> [...] If the outcome is independent of the treatment, doesn’t this also imply that the treatment has no effect? [...]

?

https://github.com/matheusfacure/python-causality-handbook/blob/3720718f8ed330f3a24100b38dd6e5a845171924/causal-inference-for-the-brave-and-true/02-Randomised-Experiments.ipynb#L29

**Comment by matheusfacure** [comment]
Good catch. You are right. I'll fix it.

**Comment by matheusfacure** [comment]
Actually no. Let me explain:
* If the outcome is independent of the treatment, then, there is no treatment effect.
* If the potential outcome is independent of the treatment, then, there is no bias, but there can still be a treatment effect.

**Comment by lgabs** [comment]
Thanks for the reply. Yeah, I had to read the paragraph with this phrase some more times :smile: :grimacing: I think I got it now :pray:
