### ISSUE TITLE
Issue on page /12-Doubly-Robust-Estimation.html

### ISSUE THREAD

**Issue by 92amartins** [matheusfacure/python-causality-handbook#136]
In the first paragraph:
> We’ve learned how to use linear regression and propensity score weighting to estimate 𝐸[𝑌|𝑌=1]−𝐸[𝑌|𝑌=0]|𝑋. But which one should we use and when? When in doubt, just use both! Doubly Robust Estimation is a way of combining propensity score and linear regression in a way you don’t have to rely on either of them.

If my understanding is right, the first line should read:
> We’ve learned how to use linear regression and propensity score weighting to estimate 𝐸[𝑌|T=1]−𝐸[𝑌|T=0]|𝑋.

with each of the individual Y expectations conditioned on T instead of Y itself.

**Comment by 92amartins** [comment]
There's also a typo at the end of the chapter:
> **One** again, we can use bootstrap and see that the variance is just slightly higher.

I'm happy to send a PR for this small fixes :)

**Comment by matheusfacure** [comment]
Thanks for the feedback and sorry for the long wait.
