### ISSUE TITLE
Issue on page /03-Stats-Review-The-Most-Dangerous-Equation.html

### ISSUE THREAD

**Issue by qphong** [matheusfacure/python-causality-handbook#137]
In the code right after the paragraph starting with "One final interesting thing about hypothesis tests is that it is less conservative than checking", the standard error of the difference is computed as
```Python
diff_se = np.sqrt(cont_se + cont_se)
```
However, I think it should be 
```Python
diff_se = np.sqrt(cont_se**2 + test_se**2)
```
Then, I think the result will be different: the 95\% confidence interval for the difference between the groups contains 0.

**Comment by matheusfacure** [comment]
Nice catch!
