### ISSUE TITLE
Issue on page /12-Doubly-Robust-Estimation.html

### ISSUE THREAD

**Issue by ieipi** [matheusfacure/python-causality-handbook#14]
In the last paragraph, there is a statment " Still, doubly robust estimation can combine those two wrong models to make them less wrong. "
can you give more details about this? because practically, in real world, both the two models are wrong/biased, in such case will the DRE be less biased( and with bigger variance?)
I've read from some documents that "If both models are slightly incorrect, doubly robust estimator can be more biased"
if that's the case, then DRE will have problems in real world.

**Comment by matheusfacure** [comment]
Apparently, DR is not necessarily better than Regression alone when both PS and regression model as misspecified. Some discussion can be found here while I write the correction:
https://stats.stackexchange.com/questions/427000/does-a-doubly-robust-estimator-magnify-bias-if-both-the-outcome-regression-and
