### ISSUE TITLE
Issue on page /17-Predictive-Models-101.html

### ISSUE THREAD

**Issue by gabrieltempass** [matheusfacure/python-causality-handbook#145]
It seems to me that both of the cascade charts are wrong, because the bars don't start where they should. Thus, providing a wrong cumulative sum. To be more specific, the first chart currently is:

<img width="300" alt="cascade-1" src="https://user-images.githubusercontent.com/41839984/134792614-27e26d19-f399-4301-8ea7-5a11fb023c6b.png">

And it should be something like:

<img width="300" alt="cascade-1-new" src="https://user-images.githubusercontent.com/41839984/134792623-5a007536-dbf7-4459-9f85-17572e9f4595.png">

Meanwhile, the second one is:

<img width="300" alt="cascade-2" src="https://user-images.githubusercontent.com/41839984/134792655-b35e7335-ebdd-4eea-b67f-5f28a39d3090.png">

But I think it should be:

<img width="300" alt="cascade-2-new" src="https://user-images.githubusercontent.com/41839984/134792662-098abede-4cbe-4c7b-935c-54382982f30d.png">

I moved the bars up and down with Photoshop just to illustrate what is the expected look. But if you don't have a better way to edit them, and you're satisfied with the result, feel free to use these new versions.

**Comment by matheusfacure** [comment]
Thanks for all the effort. I have them on a google slides :)
