### ISSUE TITLE
Chapter 12

### ISSUE THREAD

**Issue by enriquemoraayala** [matheusfacure/python-causality-handbook#146]
There is an issue on chapter 12, in the following paragraph
We’ve learned how to use linear regression and propensity score weighting to estimate 𝐸[𝑌|𝑌=1]−𝐸[𝑌|𝑌=0]|𝑋. But which one should we use and when? When in doubt, just use both! Doubly Robust Estimation is a way of combining propensity score and linear regression in a way you don’t have to rely on either of them.

It should be
𝐸[𝑌|T=1]−𝐸[𝑌|T=0]|𝑋

**Comment by matheusfacure** [comment]
Nice catch. The bug was addressed here: https://github.com/matheusfacure/python-causality-handbook/pull/148
