### ISSUE TITLE
PDF version of full book

### ISSUE THREAD

**Issue by tobanw** [matheusfacure/python-causality-handbook#147]
It would be nice to have a PDF version of the book, for reading offline or on an ereader.

Jupyter Book has [experimental support](https://jupyterbook.org/advanced/pdf.html) for building a PDF with either of two methods: via HTML or with LaTeX.

**Comment by matheusfacure** [comment]
Sadly, it doesn't render LATEX well :/ 
![image](https://user-images.githubusercontent.com/18542597/135772669-50aaa30d-325d-4d27-9495-49e55b66c343.png)

**Comment by tobanw** [comment]
Ah, what a shame! What if you use the HTML print method? I would think that should work because the "Print to PDF" button works fine to get a PDF of an individual chapter.

**Comment by tobanw** [comment]
@matheusfacure in case you missed this^^, how does printing turn out with the HTML method?
