### ISSUE TITLE
Crash Course in Graphical Models 

### ISSUE THREAD

**Issue by kctezcan** [matheusfacure/python-causality-handbook#152]
There is an issue on chapter 4, in the following paragraph

Section: Crash Course in Graphical Models

Paragraph: As a general rule, the dependence flow in the direct path from A to B is blocked when we condition on an intermediary variable C. Or, ...

It should be
The intermediate variable here is not C but B as shown in the graph above in the same section.

Or am I mistaken?

Thanks

**Comment by matheusfacure** [comment]
good point. Thanks!
