### ISSUE TITLE
Issue in chapter 06

### ISSUE THREAD

**Issue by PetrarcaBruto** [matheusfacure/python-causality-handbook#166]
There is an issue on chapter 06, in the following paragraph
Notice how the parameter estimate of educ in the grouped model is exactly the same as the one in the ungrouped data. Also, even with only 10 data points, we’ve managed to get a statistically significant coefficient. That’s because, although we have fewer points, grouping also lowers the variance by a lot. Also notice how the standard error is a bit larger, as is the t statistics.

It should be
Notice how the parameter estimate of educ in the grouped model is exactly the same as the one in the ungrouped data. Also, even with only 10 data points, we’ve managed to get a statistically significant coefficient. That’s because, although we have fewer points, grouping also lowers the variance by a lot. Also notice how the standard error is a **bit smaller and the t statistics is a bit larger.**

**Comment by matheusfacure** [comment]
Nice catch! It is being addressed
