### ISSUE TITLE
Issue in Chapter 06

### ISSUE THREAD

**Issue by shjustinbaek** [matheusfacure/python-causality-handbook#168]
There is an issue on chapter 06, in the following paragraph
First, the intercept β0. This bad boy doesn’t have a particularly interesting interpretation. It’s the expected wage when the treatment is zero (the person hasn’t graduated from 12th grade) AND the IQ is zero. Since we don’t expect IQ to be zero for anyone (actually… nevermind), this parameter is not very meaningful. Now, when we turn to β1, we have a similar situation. This parameter is how much increase in wage we should expect from completing 12th grade **when IQ is zero**. Once again, since IQ is never zero, it doesn’t have a particularly interesting meaning. Now, β2 is a bit more interesting. It tells us how much IQ increases wages **for the non-treated.** So, in our case, it is something like 0.11. This means that for each 1 extra IQ point, the person that has not completed 12th grade should expect to gain an extra 11 cents per hour.

It should be
First, the intercept β0. This bad boy doesn’t have a particularly interesting interpretation. It’s the expected wage when the treatment is zero (the person hasn’t graduated from 12th grade) AND the IQ is zero. Now, when we turn to β1, we have a similar situation. This parameter is how much increase in wage we should expect from completing 12th grade **regardless of IQ**. Now, β2 is a bit more interesting. It tells us how much IQ increases wages **regardless of treatment** 

---

I think the bolded part of the original text in chapter 6 is incorrect:
when you look at the linear regression model with interaction term,
![image](https://user-images.githubusercontent.com/46898478/142589456-72813c5b-d7bb-49cd-aeb0-c1f1e9fffc96.png)

β1*T is added to wage even if IQ is not zero
β2*IQ is also added to wage even if T is not zero

so i really don't understand how:
1. β1 is how much increase in wage we should expect from completing 12th grade **when IQ is zero**
2. β2 is how much IQ increases wages **for the non-treated.**  (T=0)

I come from a machine learning background. So maybe I misunderstood something.
please correct me if I am wrong

Also thank you so much for the great book, appreciate it!

**Comment by matheusfacure** [comment]
Hi, thanks for the feedback! Let me try to explain. We can say that "how much increase in wage we should expect from completing 12th" is actually the slope of wage on education. This slope is given by the derivative of the above model wrt education:
Slope = B1 + B3*IQ

So, B1 is the slope when IQ is zero. Or, in words, "is how much increase in wage we should expect from completing 12th grade when IQ is zero". 

If IQ is not zero, the slope is not B1 anymore, so B1 is **not** the slope regardless of IQ.

Similar thing for B2. 
The slope on IQ is B2 + B3 T. So B2 is the slope when T=0 (non treated).
