### ISSUE TITLE
Typo in chapter 7

### ISSUE THREAD

**Issue by srtaheri** [matheusfacure/python-causality-handbook#169]
There is a typo on chapter 07, in the following paragraph
𝐴𝑇𝐸=𝐸[𝑌𝑖|𝑇𝑖=1]−𝐸[𝑌𝑖|𝑇𝑖=0]

It should be
𝐴𝑇𝐸=𝐸[𝑌|𝑇=1]−𝐸[𝑌|𝑇=0]

Because the expectation is over all the individuals  not a single individual Y_i

**Comment by matheusfacure** [comment]
Good point. The fix should appear in the next release.
