### ISSUE TITLE
Typo in Chapter 6

### ISSUE THREAD

**Issue by JinwooMcLee** [matheusfacure/python-causality-handbook#171]
There is an issue on chapter 6, in the following paragraph
> More formally, when the **dependent** variable is binary, as is often the case with treatment indicators, regression captures the ATE perfectly. That is because regression is a linear approximation to the conditional expectation function (CEF)

It should be
> More formally, when the **independent** variable is binary, as is often the case with treatment indicators, regression captures the ATE perfectly. That is because regression is a linear approximation to the conditional expectation function (CEF)

Anyways, thanks for amazing work!

**Comment by matheusfacure** [comment]
Nice catch! Thanks!
