### ISSUE TITLE
Issue on page /12-Doubly-Robust-Estimation.html

### ISSUE THREAD

**Issue by scottlyden** [matheusfacure/python-causality-handbook#176]
In the code block where you deliberately mangle the propensity estimates ...

np.random.seed(88)
parallel_fn = delayed(doubly_robust_wrong_ps)
wrong_ps = Parallel(n_jobs=4)(parallel_fn(data_with_categ.sample(frac=1, replace=True), X, T, Y)
                              for _ in range(bootstrap_sample))
wrong_ps = np.array(wrong_ps)
print(f"ATE 95% CI:", (np.percentile(ates, 2.5), np.percentile(ates, 97.5)))

... you want to calculate the percentiles on wrong_ps (not ates).  The issue also occurs when you mangle the conditional mean outcome estimates (ie, you use ates instead of wrong_mux).

PS

The book is AWESOME!

**Comment by matheusfacure** [comment]
Good point! I've corrected it and it should be reflected in the next release.
