### ISSUE TITLE
Typo on Chapter 01

### ISSUE THREAD

**Issue by DionisiusMayr** [matheusfacure/python-causality-handbook#180]
There is a typo on chapter 1, in the following paragraph:
> Meanwhile, we kind of forgot about those that have been doing “old fashioned” science with data all along. During all this time, economists were trying to answer what is the true impact of education on one’s earnings, biostatisticians were trying to understand if saturated fat led to higher chance of heart attack and psychologists were trying to understand if words of affirmation led indeed to a happier marriage. If we were to be completely honest, data scientist is not a recent field. We are simply aware of it just now due to the massive amount of free marketing the media has provided.

It should be
> Meanwhile, we kind of forgot about those that have been doing “old fashioned” science with data all along. During all this time, economists were trying to answer what is the true impact of education on one’s earnings, biostatisticians were trying to understand if saturated fat led to higher chance of heart attack and psychologists were trying to understand if words of affirmation led indeed to a happier marriage. If we were to be completely honest, data science is not a recent field. We are simply aware of it just now due to the massive amount of free marketing the media has provided.

(data scientist -> data science)

**Comment by matheusfacure** [comment]
Nice catch!
