### ISSUE TITLE
Issue on page /20-Plug-and-Play-Estimators.html

### ISSUE THREAD

**Issue by JinwooMcLee** [matheusfacure/python-causality-handbook#181]
In target transformation part,

I think the equation of
<img src="https://render.githubusercontent.com/render/math?math=Y_i*T_i = Y_(1)i*T_i \text{ and }  Y_i*(1-T_i) = Y_(0)i*T_i">

should be
<img src="https://render.githubusercontent.com/render/math?math=Y_i*T_i = Y(1)_{i}*T_i \text{ and }  Y_i*(1-T_i) = Y(0)_{i}*(1-T_i)">

`Y_i*T_i = Y(1)_{i}*T_i \text{ and }  Y_i*(1-T_i) = Y(0)_{i}*(1-T_i)`

Thanks!

**Comment by matheusfacure** [comment]
Nice catch! Thanks!
