### ISSUE TITLE
Minor correction in Chapter 06 - Grouped and Dummy Regression

### ISSUE THREAD

**Issue by jakubkaplan** [matheusfacure/python-causality-handbook#183]
Thank you for putting the guide together! It is great so far!

There is an issue on Chapter 06 - Grouped and Dummy Regression, in the following paragraph
> The parameter estimate is larger. What is happening here is that the regression is placing equal weight for all points. If we plot the model along the grouped points, we see that the non weighted model is giving more importance to small points in the lower left than it should. As a consequence, the line has a higher slope.

It should be (changes highlighted in bold):
> The parameter estimate is **smaller**. What is happening here is that the regression is placing equal weight for all points. If we plot the model along the grouped points, we see that the non weighted model is giving more importance to small points in the lower left than it should. As a consequence, the line has a **lower** slope.

**Comment by matheusfacure** [comment]
Nica catch! Thanks!
