### ISSUE TITLE
Minor Typo in 22 - Debiased/Orthogonal Machine Learning 

### ISSUE THREAD

**Issue by pan5431333** [matheusfacure/python-causality-handbook#184]
There is an issue on chapter XXX, in the following paragraph
Fit a model $M_x(X)$ to predict the treatment from the covariates X and get out of fold residuals

It should be
Fit a model $M_t(X)$ to predict the treatment from the covariates X and get out of fold residuals

**Comment by matheusfacure** [comment]
I don't remember when, but it looks like I've fixed it 
![image](https://user-images.githubusercontent.com/18542597/158072359-fce2e0fc-da3f-4c82-a0d3-43caa503c7a9.png)
