### ISSUE TITLE
Some chapters have chapters 13 and 14 missing from the table of contents on the left-hand side and from the next-chapter navig

### ISSUE THREAD

**Issue by jakubkaplan** [matheusfacure/python-causality-handbook#185]
There is an issue on chapter 12, specifically if you look at the table of contents on the left, or look for "next chapter" link at the bottom, there is none, because the table of contents in this chapter is missing chapters 13 and 14:
https://matheusfacure.github.io/python-causality-handbook/12-Doubly-Robust-Estimation.html

If you go on the main landing page, chapters 13 and 14 are in the TOC:
https://matheusfacure.github.io/python-causality-handbook/landing-page.html

**Comment by matheusfacure** [comment]
Humm, I think the situation is normalized. I guess this is a bug on jupyter books side. I had a similar issue when publishing chapter 23. For reference, I had to delete the _build directory and regenerate everything again.
![image](https://user-images.githubusercontent.com/18542597/151769952-11f0c31d-b93f-4ef9-bcdc-f262a8df0a98.png)

**Comment by jakubkaplan** [comment]
Thank you! Confirming that I also see the chapters in "production" now when looking at chapter 12.
