### ISSUE TITLE
Chapter 11

### ISSUE THREAD

**Issue by attibalazs** [matheusfacure/python-causality-handbook#188]
There is a small issue in Chapter 11

Simply comparing those with and without the intervention, we can see that the treated have an achievement score that is, on average, 0.6261 (0.4723 + 0.1538) higher than the untreated.

It should be
Simply comparing those with and without the intervention, we can see that the treated have an achievement score that is, on average, 0.3185 (0.4723 - 0.1538) higher than the untreated.

**Comment by matheusfacure** [comment]
Those numbers are hard to maintain. I often update the code and forget the texts... Thanks!
