### ISSUE TITLE
Chapter 06

### ISSUE THREAD

**Issue by theo-vele** [matheusfacure/python-causality-handbook#190]
There is an issue on chapter 06, in the following paragraph

"The first one will get an increase of 1.44 in wage (60 * 0.024), while the person with 140 IQ will gain an extra 3.36 dollars (**60** * 0.024) when graduating from 12th grade"

It should be
"The first one will get an increase of 1.44 in wage (60 * 0.024), while the person with 140 IQ will gain an extra 3.36 dollars (**140** * 0.024) when graduating from 12th grade."

**Comment by matheusfacure** [comment]
nice catch!
