### ISSUE TITLE
Chapter 15

### ISSUE THREAD

**Issue by dimitris1ps** [matheusfacure/python-causality-handbook#201]
There is an issue on chapter 15, at making-inference
the function `synthetic_control` has a redundant parameter. More specifically you don't need the `pool` parameter in
```
def synthetic_control(state: int, pool: List[int], data: pd.DataFrame) -> np.array:
```

Also, it needs to be removed from the subsequent calls 
```
control_pool = cigar["state"].unique()

synthetic_control(1, control_pool, cigar).head()

parallel_fn = delayed(partial(synthetic_control, pool=control_pool, data=cigar))

```
All `control_pool` are not needed since they are not used within the `synthetic_control` function.

the function should just be 

```
def synthetic_control(state: int,  data: pd.DataFrame) -> np.array:
  
```

**Comment by matheusfacure** [comment]
Nice! Thanks for the tip!
