### ISSUE TITLE
Issue on page /22-Debiased-Orthogonal-Machine-Learning.html

### ISSUE THREAD

**Issue by ynericli** [matheusfacure/python-causality-handbook#204]
typo "cientifict", should be scientific
> To solve that, there is a final idea. Keep in mind that this idea is much less cientifict than the things we’ve seen before. It boils down to using a S-learner after applying the orthogonalization procedure, but I’m getting ahead of myself. Let’s look at that next.

**Comment by matheusfacure** [comment]
You are right. thanks!
