### ISSUE TITLE
Chapter 9

### ISSUE THREAD

**Issue by ekanol** [matheusfacure/python-causality-handbook#205]
There is an issue on chapter 9, in the following paragraph
[Up on the causal graph, you have the push assignment...] 

There is an "s" missing in the following sentence: "Since people with older phones are the one that don’t get the push, you can argue that income is also causing push delivery." 

It should be
[Since people with older phones are the one**s** that don’t get the push, you can argue that income is also causing push delivery.] 

Also further down a "to" is missing:
"As it turns out, it is not. Because of non compliance, the outcome of those assigned to the treatment will be pushed in the direction of the outcome of those assigned the control."

It should be:
"As it turns out, it is not. Because of non compliance, the outcome of those assigned to the treatment will be pushed in the direction of the outcome of those assigned **to** the control."

**Comment by matheusfacure** [comment]
Thanks!
