### ISSUE TITLE
Issue on page /04-Graphical-Causal-Models.html

### ISSUE THREAD

**Issue by rgramillano** [matheusfacure/python-causality-handbook#211]
Not an issue as much as a suggestion--could you please clarify the difference between the (⊥⊥) symbol to represent conditional independence and the (⊥) symbol used in the activities? It is just somewhat confusing to switch between the symbols in the same lesson. Appreciate it

**Comment by matheusfacure** [comment]
It's just that latex rendering in Jupyter notebook sucks. I can render the ⊥⊥ with `\!\perp\!\!\!\perp `, but not inlines. But thanks for the heads up. I'll use just ⊥ to avoid confusion.
