### ISSUE TITLE
Chapter 1

### ISSUE THREAD

**Issue by xiaowei-zhang** [matheusfacure/python-causality-handbook#212]
There is an issue on chapter 1, in the following paragraph

> Also, if the treated and the untreated only differ on the treatment itself, that is, E[Y0|T=0] = E[Y0|T=1]

It should be

> Also, if the treated and the untreated only differ on the treatment itself, then E[Y0|T=0] = E[Y0|T=1]

Reason is that those two statements are not equal. The formula is a necessary but not sufficient condition.

**Comment by matheusfacure** [comment]
Fair point.
