### ISSUE TITLE
Issue on page /11-Propensity-Score.html

### ISSUE THREAD

**Issue by stanton119** [matheusfacure/python-causality-handbook#214]
Hi,

Thanks for the great book!!

I was looking at the achievement score test in the first section, and not sure if I have understood this the wrong way round or not:

We have an intercept of -0.1538 and a treatment coefficient of 0.4723. Doesn't the treatment coefficient denote the average difference between the treated and non-treated? If that is the case I think the wording in the following paragraph is the wrong way round. 0.3185 would be the average of the treated group above the average student. And -0.1538 would be the average of the non-treated group compared with the average.

> Simply comparing those with and without the intervention, we can see that the treated have an achievement score that is, on average, **0.3185 (0.4723 - 0.1538)** higher than the untreated. But is this big or small? I know that interpreting standardised outcomes can be challenging, but bear with me for a moment. I think it is worth going through this because it won’t be the last time you will encounter standardized scores.

> The outcome variable being standardised means that it is measured in standard deviations. So, the treated are 0.3185 deviations above the untreated.

Should it be?:
> achievement score that is, on average, **0.4723** higher than the untreated

**Comment by matheusfacure** [comment]
You are absolutely right, it should read:
> Simply comparing those with and without the intervention, we can see that the treated have an achievement score that is, on average, 0.3185 (0.4723 - 0.1538) higher than the **average score** (which is zero, since the score is standardized). But is this big or small? I know that interpreting standardized outcomes can be challenging, but bear with me for a moment. I think it is worth going through this because it won't be the last time you will encounter standardized scores.

Thanks for the feedback.
