### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by JacobWren** [matheusfacure/python-causality-handbook#220]
Hello,

When using IV2SLS.from_formula(formula, data).fit(), have you ever ran into the error: "ValueError: regressors [exog endog] do not have full column rank"?

It seems to be triggered when a dummy variable has too many categories. Not sure of a work around.

Thanks.

**Comment by matheusfacure** [comment]
yes. The issue arises when a column is a linear combination of another, like in the case where you don't drop one of the dummy columns. I'm closing this because it concerns other software ok? Check out here https://github.com/jmbejara/comp-econ-sp18/issues/73
