### ISSUE TITLE
Issue in ATT = ATE in chapter 1

### ISSUE THREAD

**Issue by JacksonRudd** [matheusfacure/python-causality-handbook#230]
There is an issue on chapter 01, in the following paragraph
"""
Not only that, but E(Y1-Y0 | T=1) = E(Y1-Y0 | T=0), simply because the treated and untreated are exchangeable. Hence, in this case, the difference in means BECOMES the causal effect:
"""
At this point we only know that E(Y0|T=1) = E(Y0|T=0). aka we know there is no bais. 

Therefore we still need to prove that E(Y1| T=1) = E(Y1 | T=0) to show that  E(Y1-Y0 | T=1) = E(Y1-Y0 | T=0). Maybe this is obvious and I'm missing something, but I think the section would be improved by proving this. I am somewhat doubtful this is true.

**Comment by Henniez-SwissWater** [comment]
I agree
An example would be where the group T=0 reacts more strongly on the treatment than group T=1. So the differences wouldn't be equal, even though thenon bias equation still holds.
I think you need a stronger assumptions (maybe on the distribution and not just the expected value).

**Comment by matheusfacure** [comment]
You are right. Beyond `E[Y0 | T=0] =  E[Y0 | T=1]`, you also need `E[Y1 | T=0] =  E[Y1 | T=1]`. Both are satisfied under randomization, but this isn't clearly state in the chapter. Thanks!
