### ISSUE TITLE
Chapter 21 - Fitting the propensity score of the T-Learner

### ISSUE THREAD

**Issue by AxelAgue** [matheusfacure/python-causality-handbook#242]
Hello!
I think there is an issue on chapter 21, when fitting the propensity score of the T-Learner, in the following code section:
```
# fit the propensity score model
ps_m = LogisticRegression(solver="lbfgs", penalty='none')
ps_m.fit(train[X], train[y])
ps_score = ps_m.predict_proba(train[X])
```

It should be
```
# fit the propensity score model
ps_m = LogisticRegression(solver="lbfgs", penalty='none')
ps_m.fit(train[X], train[T])
ps_score = ps_m.predict_proba(train[X])
```
Since, as far as I know, with this propensity score model we are trying to predict the probability of receiving the treatment.

**Comment by matheusfacure** [comment]
This issue was solved here #218
