### ISSUE TITLE
Issue on page /Conformal-Inference-for-Synthetic-Control.html

### ISSUE THREAD

**Issue by rameshiyerv** [matheusfacure/python-causality-handbook#247]
Hey Guys!

The cell where you are trying to call the fn "residuals" I believe there is a typo.

![image](https://user-images.githubusercontent.com/64004013/175056194-9941fd4c-d521-462a-9280-41d25c23d009.png)

**should it instead be:
model = SyntheticControl()**
since we are passing model in the function call or am i miss understanding it?

**Comment by matheusfacure** [comment]
Ops. You are correct! Thanks!

**Comment by rameshiyerv** [comment]
I really liked this chapter & have some more thought on how to make it bit easier to understand (especially Data Scientist coming from Computer Science background). 

Any chance you can share the pre-processed smoking.csv file. 

I can run the whole notebook & the consolidate my suggestions in one go...
