### ISSUE TITLE
Standard Deviation formula

### ISSUE THREAD

**Issue by danieljwilson** [matheusfacure/python-causality-handbook#248]
There is an issue on chapter 03, in the following paragraph

>![image](https://user-images.githubusercontent.com/7377893/175162826-a4db814f-9275-43e3-bc8d-35f09d07dca7.png)

The formula seems to suggest it is calculating the variance when it is calculating the standard deviation. (i..e. sigma should not be squared)

I also think that as a more general note you have been talking about standard error and then all of a sudden you introduce standard deviation out of the blue. In the first sentence you state that we are going to calculate SE but next you say lets calculate standard deviation. As an uninformed reader I think it could be easy to miss that jump or not follow, so perhaps you could take a beat to explain what std is and why it is necessary for SE...ie. how it connects.

**Comment by daneshmand-uber** [comment]
In addition, the sum is over N+1 samples which is wrong and should be N (would also be more readable if you add a subscript i to x).

**Comment by matheusfacure** [comment]
Thanks for the feedback!
