### ISSUE TITLE
Chapter 22: Reason for calling it R-Learner

### ISSUE THREAD

**Issue by MatthiasLuxQC** [matheusfacure/python-causality-handbook#250]
There is an issue in chapter 22, in the following paragraph
Nie and Wager called it the R-Learner, as a way to recognise the work of Donald Rubin in the causal literature.

It should be (see p. 3 just after formula (4) in Nie and Wager (2020))
Nie and Wager called it the R-Learner, as a way to recognise the work of Robinson (1988) and to emphasize the role of residualization.

**Comment by matheusfacure** [comment]
Thanks for the correction!
