### ISSUE TITLE
Question on page /22-Debiased-Orthogonal-Machine-Learning.html

### ISSUE THREAD

**Issue by teemingyi** [matheusfacure/python-causality-handbook#252]
Hi, just wanted to ask a question on the section CATE Estimation with Double-ML.

For the final CATE model, I noticed that the formula did not include a term for the covariates **Xi**.

I was wondering if it is necessary to include the covariates in the CATE model. 
By the codes, I think they are already included by default.

I am comparing this formula with the one used in chapter 18, under the section Predicting Elasticity.

**Comment by matheusfacure** [comment]
Could you be more specific on where is the issue? Looking at the chapter, Xi is in there

![image](https://github.com/matheusfacure/python-causality-handbook/assets/18542597/0844af73-78b3-47cc-baee-b7f011e9e295)
