### ISSUE TITLE
Chapter 09 still has references for "compilers"

### ISSUE THREAD

**Issue by fithisux** [matheusfacure/python-causality-handbook#255]
There is an issue on chapter 9, in the following paragraph

 In other words, this is the compiler population. Just so we can remember, Compilers means that 

It should be

 In other words, this is the complier population. Just so we can remember, Compliers means that

**Comment by ayhteo** [comment]
👍  Addressed this in https://github.com/matheusfacure/python-causality-handbook/pull/279
