### ISSUE TITLE
Issue on page /19-Evaluating-Causal-Models.html

### ISSUE THREAD

**Issue by pgmeiner** [matheusfacure/python-causality-handbook#259]
I find the chapter about evaluating causal models very interesting and inspiring. I have not seen that before. 
However, sometimes I struggle with the terminology a bit. But maybe it is just my misunderstanding and you can help me here.
When you talk about elasticity and estimate it with a linear regression aren't you actually estimating the partial slope (I also have sometimes the feeling you use elasticity and slope in exchange)?
When elasticity between Y and T is defined as follows
e = \partial Y / \partial T * T/Y then the actual calculation would look like:
e = \partial Y / \partial T * T/Y = \partial (log(Y)) / \partial (log(T)) which would lead to log(Y) = log(beta_0) + e*log(T)
So for estimating the elasticity e we would need to use log(Y) and log(T) instead of Y and T alone in the linear regression.
If I misunderstood something please let me know.
best regards
Peter

**Comment by matheusfacure** [comment]
You are right. I've replaced elasticity with sensitivity to avoid the confusion.
