### ISSUE TITLE
Issue on page /03-Stats-Review-The-Most-Dangerous-Equation.html

### ISSUE THREAD

**Issue by gabriel-solon-padilha** [matheusfacure/python-causality-handbook#264]
The LATEX formating on the SE in this paragraph on the Hypothesis test is broken 

"With this at hand, we can say that we are 95% confident that the true difference between the online and face-to-face groups falls between -8.37 and -1.44. We can also construct a z statistic by dividing the difference in mean by the $SE\$ of the differences"

**Comment by matheusfacure** [comment]
I couldn't reproduce the issue. It looks like this to me:
![image](https://github.com/matheusfacure/python-causality-handbook/assets/18542597/927e27b2-66a6-49a7-ab73-aeef8dae7c1c)
