### ISSUE TITLE
Issue on page /01-Introduction-To-Causality.html

### ISSUE THREAD

**Issue by bongho** [matheusfacure/python-causality-handbook#268]
In the section "When Association IS Causation", for the first code, when clicking "Click to hide", "Click to hide" sentence is included in the code paragraph

<img width="764" alt="image" src="https://user-images.githubusercontent.com/30528502/189640575-9846c242-5412-4ee2-afac-36a201f8dec2.png">

**Comment by matheusfacure** [comment]
I think this was solved.
