### ISSUE TITLE
Issue on page /05-The-Unreasonable-Effectiveness-of-Linear-Regression.html

### ISSUE THREAD

**Issue by bongho** [matheusfacure/python-causality-handbook#274]
In the following code section, I don't think "import graphviz as gr" is required. :)

Click to hideimport warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import graphviz as gr
%matplotlib inline

**Comment by matheusfacure** [comment]
Yes it is. It is used to show the DAG in the OVB section.
