### ISSUE TITLE
wrong reference to plot

### ISSUE THREAD

**Issue by fojeda** [matheusfacure/python-causality-handbook#29]
There is an issue on chapter 06-Grouped-and-Dummy-Regression, in the following paragraph
The parameter estimate is larger. What is happening here is that the regression is placing equal weight for all points. If we plot the model along the grouped points, we see that the non weighted model is giving more importance to small points in the lower right than it should. As a consequence, the line has a higher slope.
It should be
The parameter estimate is larger. What is happening here is that the regression is placing equal weight for all points. If we plot the model along the grouped points, we see that the non weighted model is giving more importance to small points in the lower **left** than it should. As a consequence, the line has a higher slope.

**Comment by matheusfacure** [comment]
Nice catch!

**Comment by fojeda** [comment]
im enjoying the reading! great job!
