### ISSUE TITLE
Issue on page /21-Meta-Learners.html

### ISSUE THREAD

**Issue by RyanBaten** [matheusfacure/python-causality-handbook#307]
There is a potential issue on chapter 21, in the following paragraph

Here, they plot the difference between the true causal effect (red outline) and the estimated causal effect, 
$\tau - \hat{\tau}$, using an S-learner. The estimated causal effect is heavily downward biased ( $\tau - \hat{\tau} \gt 0$ most of the time). In other words, the true causal effect is frequently bigger than the estimated one.

Improvement:

Here, they plot the difference between the estimated causal effect and the true causal effect (red outline), 
$\hat{\tau} - \tau$, using an S-learner. The estimated causal effect is heavily biased ( $\hat{\tau} - \tau \gt 0$ most of the time).

Explanation:

The paper mentions the plot shows simulated distribution for estimator $\hat{\theta_{0}} - \theta_{0}$ (centered at true value $\theta_{0}$) and the simulated distribution is shifted right compared to a normal approximation derived under the assumption of no bias. 
Guessing the causal effect found was negative so regularization biasing the treatment effect to 0 means a positive difference when subtracting the true value from the ml estimated one. This makes this part of the text confusing in this passage since it mentions a downward bias but shows a positive difference in the plot.
I'm not quite sure the best way to re-word this or if this interpretation is correct. If not, let me know and I'm sure this will be a good learning experience.

**Comment by matheusfacure** [comment]
Good point!
