### ISSUE TITLE
Chapter 20: Unconfoundedness notation

### ISSUE THREAD

**Issue by TDebono** [matheusfacure/python-causality-handbook#310]
I'm unsure about a specific expression for unconfoundedness assumption in Chapter 20/Target Transformation. In the 4th (or 5th, depending on how you count) paragraph, this assumption is expressed as:

```math
T || Y(1), Y(1)
```

Should this not be: 

```math
T || Y(1), Y(0)
```

**Comment by matheusfacure** [comment]
You are right. It was a typo. Thanks!
