### ISSUE TITLE
Ch 17 - intuition

### ISSUE THREAD

**Issue by maswiebe** [matheusfacure/python-causality-handbook#326]
I think you should give more intuition for the gradient boosting model results in this graph:

![image](https://user-images.githubusercontent.com/8338689/236062869-b9471a33-5c0d-450f-8dda-e57b5aef56ed.png)

For the region model, you're estimating the net value by region. But for the gradient boosting model, are you estimating it by subsets of feature space (Age X Income X Region)?

**Comment by matheusfacure** [comment]
In both cases you are estimating the net value by groups. For the prediction model, the groups are defined by the model's prediction.
Next, you use those net values estimates to set up a policy. For the prediction model, this simply means treating the regions where prediction>0. Doing this gives the blue histogram.
