### ISSUE TITLE
Issue on page /12-Doubly-Robust-Estimation.html

### ISSUE THREAD

**Issue by andytimm** [matheusfacure/python-causality-handbook#330]
I believe this is a typo, unless I’m missing something.

![8FFF63A0-9DC9-4CDE-9A76-50366DE1182D](https://github.com/matheusfacure/python-causality-handbook/assets/12973310/aee805d9-1964-42f4-a12b-9efb3e920ce7)

I believe between lines 2 and 3, you are factoring out a u(Xi) from the last two terms, and then further pulling out a -1 from both terms in parens to set up the next line. 

But that -1 then disappears when it shouldn’t, and so I believe the minus between the fractions in the last line should actually be a plus.

**Comment by matheusfacure** [comment]
> and then further pulling out a -1 from both terms in parens to set up the next line.

No. From line 3 to 4, I'm just finding the common denominator of T/P and 1
```
T/P - 1 = T/P - P/P = (T-P)/P
```
