### ISSUE TITLE
Issue on page /13-Difference-in-Differences.html

### ISSUE THREAD

**Issue by curtis-lu** [matheusfacure/python-causality-handbook#336]
Should this:

<img width="600" alt="image" src="https://github.com/matheusfacure/python-causality-handbook/assets/59253082/a97114c5-52ee-42a7-bb40-c56c97e32c5c">

be changes to this:

<img width="615" alt="image" src="https://github.com/matheusfacure/python-causality-handbook/assets/59253082/c84e1ea0-9e17-4344-a1f7-d013a748fabb">

?

**Comment by matheusfacure** [comment]
Thanks!
