### ISSUE TITLE
Issue on page /Debiasing-with-Propensity-Score.html

### ISSUE THREAD

**Issue by jeffCollinsLM** [matheusfacure/python-causality-handbook#338]
Just a comment/question on propensity score vs DML in the case of a binary treatment.  When the treatment is binary I think the DML stage 1 treatment model becomes a treatment propensity model (the probability of receiving the treatment.)  If this probability is recorded in the data as part of the experimental design, we can just use the recorded value in lieu of fitting the S1 treatment model, correct?  So I don't see an advantage of propensity score over DML in this case.

It seems like the main 'advantage' of propensity score modeling is it forces you to look very closely at the data making all of those distribution plots, which helps to gain understanding of how well the positivity assumption is holding.

**Comment by matheusfacure** [comment]
> If this probability is recorded in the data as part of the experimental design, we can just use the recorded value in lieu of fitting the S1 treatment model, correct?
Correct.

>So I don't see an advantage of propensity score over DML in this case.
Not so much. DML has a debiasing model (which you don't need if you store the ps), but also a denoising model that estimates Y - E[Y|X]. This reduces the variance of the estimator, compared to just using the IPW.
