### ISSUE TITLE
Issue on page /01-Introduction-To-Causality.html

### ISSUE THREAD

**Issue by Henry-Louis** [matheusfacure/python-causality-handbook#339]
I found there may be a typo for the expression of Average Treatment Effect 
"""Finally, we reorder the terms, merge some expectations, and lo and behold:
 
  (The Expression here seems to be wrong)

This simple piece of math encompasses all the problems we will encounter in causal questions. """

**Comment by matheusfacure** [comment]
I'm assuming you means this expression? 
![image](https://github.com/matheusfacure/python-causality-handbook/assets/18542597/00ac202a-fb07-4d9d-ace9-2b4977fb4e09)
I could't find the mistake. Can you be more specific?
