### ISSUE TITLE
Intuition behind 𝜅

### ISSUE THREAD

**Issue by mpjan** [matheusfacure/python-causality-handbook#4]
There's this line:

> We can show that the impact of T on `Z` is equal to the impact of Z on Y, scaled by the impact of Z on T.

I'm confused, shouldn't it be `Y` instead of `Z`? Such that: "We can show that the impact of T on `Y` is equal to the impact of Z on Y, scaled by the impact of Z on T."

**Comment by mpjan** [comment]
I'm referring to the `08-Instrumental-Variables.ipynb` notebook

**Comment by matheusfacure** [comment]
Yup. You'r right! Nice catch!
