### ISSUE TITLE
Chapter 10

### ISSUE THREAD

**Issue by dwitvliet** [matheusfacure/python-causality-handbook#41]
There is an issue in [Chapter 10 on github.io](https://matheusfacure.github.io/python-causality-handbook/10-Matching.html), in the last paragraph of The Subclassification Estimator:

`\\\\(\\bar{Y}_{k1}\\\\)` and `\\\\(\\bar{Y}_{k0}\\\\)` are not shown as equations, but simply as raw text (`\(\bar{Y}{k1}\)` and `\(\bar{Y}{k0}\)`). 

It's an odd error, as the equations are correctly shown in my local jupyter environment.

**Comment by matheusfacure** [comment]
Jupyter notebook renders some equation that Jupyter books sometimes doesn't... It's a pain to catch those, but I think I can fix it. I'll take a look, thks.
