### ISSUE TITLE
Question chapter 1: how to equate ATET to ATE

### ISSUE THREAD

**Issue by willemvdb42** [matheusfacure/python-causality-handbook#49]
In the first chapter "Introduction to causality" (in subchapter "Bias") you state that given
E[Y0|T=0] = E[Y0|T=1]
we can deduct that
E[Y|T=1] − E[Y|T=0] = E[Y1 − Y0|T=1].

However, a few lines later you state:
E[Y|T=1] − E[Y|T=0] = ATE = ATET
In other words you say:
E[Y|T=1] − E[Y|T=0] = E[Y1−Y0] = E[Y1−Y0|T=1]

I can see why E[Y|T=1] − E[Y|T=0] = E[Y1−Y0|T=1] since you derive it. But I can't figure out why this would also be equal to E[Y1−Y0] (the overall average treatment effect). Do you not also need that E[Y1|T=0] = E[Y1|T=1]? If so why not? Could you elaborate? I think the easiest and clearest way to show this would be to just show the mathematical derivation from E[Y1−Y0] to either E[Y1−Y0|T=1] or E[Y|T=1] − E[Y|T=0].

Intuitively there also seems to be something missing for me. In your own words: E[Y0|T=0] = E[Y0|T=1] is to say that treatment and control group are comparable before the treatment. But this condition, intuitively, does not seem sufficient to say that E[Y1−Y0|T=1] = E[Y1−Y0|T=0]. Because both groups may indeed be comparable before the treatment, but the effect of the treatment might still be quite different for both groups. So in order to state E[Y1−Y0|T=1] = E[Y1−Y0|T=0], I intuitively feel another condition needs to be fulfilled, which is that the effect of the treatment is the same for both groups. In other words: E[Y1|T=0] = E[Y1|T=1]. But perhaps I am missing something?

**Comment by matheusfacure** [comment]
Hummm I see the confusion. I'll try to add an extra line of derivation that goes from the ATET to the ATE.

The fact that T=1 and T=0 are exchangeable can be used to show that difference in means is the ATET AND that the ATET is the ATE:
Due to exchangeability, we have that E[Y0|T=0]=E[Y0|T=1] so
E[Y|T=1] - E[Y|T=0] = E[Y_1 - Y_0|T=1], because the bias term would vanish. Here, difference in means is the ATET.
But exchangeability also implies that E[Y1|T=0]=E[Y1|T=1]. Essentially, it means that you can swap conditioning on T=0 to T=1, which gives the second derivation that you are missing. E[Y_1 - Y_0|T=1] = E[Y_1 - Y_0|T=0] = E[Y_1 - Y_0]

**Comment by willemvdb42** [comment]
I see that you added a part that says "E[Y_1 - Y_0|T=1]=E[Y_1 - Y_0|T=0], simply because the treated and untreated are exchangeable".

Thank you for your answer so far, but to my eyes this is not a sufficient explanation. For example what do you mean by "the treated and untreated are exchangeable"?

Option 1: Do you mean that the way we assign 1 and 0 to treatment is arbitrary and can be exchanged? (So T=1 --> T=0 and T=0 --> T=1) I agree you can do this, but it does not mean that E[Y_1 - Y_0|T=1]=E[Y_1 - Y_0|T=0]. Because when you change the assignment of the treatment you also change the condition you have, which is to say:  
E[Y_0|T=0] = E[Y_0|T=1] --> E[Y_1|T=0] = E[Y_1|T=1]. 
And in that case the derivation becomes: 
E[Y|T=1] - E[Y|T=0] = E[Y_1|T=1] - E[Y_0|T=0] + E[Y_0|T=1] - E[Y_0|T=1]
                               = E[Y_1 - Y_0|T=1] - E[Y_0|T=0] + E[Y_0|T=1]
But now the bias term cannot be eliminated anymore because you no longer have the condition E[Y_0|T=0] = E[Y_0|T=1], instead you have the condition E[Y_1|T=0] = E[Y_1|T=1]. The only thing you can say is that:
E[Y|T=1] - E[Y|T=0] = E[Y_1|T=1] - E[Y_0|T=0]
                               = E[Y_1|T=1] - E[Y_0|T=0] + E[Y_1|T=0] - E[Y_1|T=0]
                               = E[Y_1 - Y_0|T=0] + E[Y_1|T=1] - E[Y_1|T=0]
Now we can use the updated condition E[Y_1|T=0] = E[Y_1|T=1] to get:
E[Y|T=1] - E[Y|T=0] = E[Y_1 - Y_0|T=0]
But this is exactly the same as what we already derived before we made the change of T=1 --> T=0 and T=0 --> T=1. So this tells us nothing new.

Option 2: Do you mean that because E[Y_0|T=0] = E[Y_0|T=1] both groups are comparable before receiving the treatment, and therefore exchangeable? If so I also don't agree with this. Both groups might be comparable before applying the treatment. But the way they react to the treatment might still differ.

Honestly, the more I think about it the more I'm starting to think that the condition E[Y_0|T=0] = E[Y_0|T=1] is not sufficient to say that 
E[Y|T=1] - E[Y|T=0] = E[Y_1 - Y_0].
An example I could think of is this: suppose you again have a sample of schools, some of which gave tablets to their students. As before let's again assume that the more rich a school is, the more likely they are to hand out tablets. But for the sake of argument let's now assume that the academic performance before handing out tablets was more or less the same (same mean, with a random error) for all the schools regardless of how rich they are. In that case the condition E[Y_0|T=0] = E[Y_0|T=1] holds. But now it is possible to imagine that the children in rich schools are wealthy enough that they don't care about tablets anymore, so they treat them poorly and easily lose or break them. But the children of less rich schools actually value their tablets a lot and love working on them. In that case the effect of the treatment would be different for both groups. In other words E[Y_1 - Y_0|T=0] is not equal to E[Y_1 - Y_0|T=1]!

Maybe there is a mistake in my reasoning. I would appreciate it if you could point it out to me! Or if you have an exact mathematical derivation to show that E[Y|T=1] - E[Y|T=0] = E[Y_1 - Y_0] using only E[Y_0|T=0] = E[Y_0|T=1] I would like to go over that as well.

In any case thanks for you answer so far!
