### ISSUE TITLE
Issue on page /16-Regression-Discontinuity-Design.html

### ISSUE THREAD

**Issue by M46F** [matheusfacure/python-causality-handbook#52]
Hi, seems the causal effect at the threshold is not rendered properly in the github.io
links:
https://matheusfacure.github.io/python-causality-handbook/16-Regression-Discontinuity-Design.html#rdd-estimation

image:
![image](https://user-images.githubusercontent.com/17894752/111324550-74a6ad80-869d-11eb-97bf-4dfbe517d7b7.png)

**Comment by matheusfacure** [comment]
Hummm, this renders OK on jupyter notebooks. It appears to be some sort of bug with jupyter books. I'll take a look
