### ISSUE TITLE
Issue on page /04-Graphical-Causal-Models.html

### ISSUE THREAD

**Issue by vicflair** [matheusfacure/python-causality-handbook#56]
Small typo (or bug). The text says: "First, look at this very simple graph. A causes B which causes C. Or X causes Y which causes Z." But the graph shows A --> C --> B instead.
<img width="645" alt="Screen Shot 2021-03-20 at 16 02 00" src="https://user-images.githubusercontent.com/7283382/111863284-9ce02600-8995-11eb-8f2f-58c27237acd6.png">

**Comment by matheusfacure** [comment]
Thanks for the notice. This has been addressed in this pr https://github.com/matheusfacure/python-causality-handbook/pull/51/files
