### ISSUE TITLE
Issue: Chapter Beyond Confounders

### ISSUE THREAD

**Issue by farhanreynaldo** [matheusfacure/python-causality-handbook#62]
There is an issue on chapter Beyond Confounders, in the following paragraph

<img width="808" alt="image" src="https://user-images.githubusercontent.com/8732795/112753372-92f79c00-9001-11eb-9629-1930bae76669.png">

I think it should be `T_i = 0` on the right hand side. But if I incorrectly raise this issue, you may close it immediately.

**Comment by matheusfacure** [comment]
No, you are right. That difference written there is zero hehe
