### ISSUE TITLE
Issue on page /15-Synthetic-Control.html

### ISSUE THREAD

**Issue by ngatia-m** [matheusfacure/python-causality-handbook#77]
Would you kindly share the smoking.csv file?

**Comment by matheusfacure** [comment]
Sure! All te files are in this repository under https://github.com/matheusfacure/python-causality-handbook/tree/master/causal-inference-for-the-brave-and-true/data

Also, for the simulated data, this notebook has the simulating functions
https://github.com/matheusfacure/python-causality-handbook/blob/master/Simulated-Data.ipynb
