### ISSUE TITLE
social image

### ISSUE THREAD

**Issue by microprediction** [matheusfacure/python-causality-handbook#81]
Set the social image in github settings so that that cool splash image on the readme appears when someone posts it on LI or whatever.

**Comment by matheusfacure** [comment]
![image](https://user-images.githubusercontent.com/18542597/118408604-b1bafc00-b65c-11eb-9f07-af88f7d90229.png)
Thats weird... Apparently, it is set already. But it doesn't show when I post on on Li...
Any ideas what might be happening?
