### ISSUE TITLE
treated/untreated wrong way round?

### ISSUE THREAD

**Issue by ZacharyForrest** [matheusfacure/python-causality-handbook#85]
There is an issue on chapter 7 , in the following paragraph

When we do that, the treated and control are no longer comparable. As we can see, the **treated** is now only composed of the segment of customers that will spend even without the campaign. Also notice that we can even know the direction of the bias here.

It should be (right?)

When we do that, the treated and control are no longer comparable. As we can see, the **untreated** is now only composed of the segment of customers that will spend even without the campaign. Also notice that we can even know the direction of the bias here.

**Comment by matheusfacure** [comment]
Right! Thks for the feedback! Should be fixed once I release the next chapter.

**Comment by ZacharyForrest** [comment]
Forgot to say: love the book and thank you!
