### ISSUE TITLE
Grammar correction in Chapter 1 subheading "Key Ideas" ; first paragraph

### ISSUE THREAD

**Issue by benadaba** [matheusfacure/python-causality-handbook#90]
There is an issue on chapter 1, in the following paragraph:

So far, we’ve seen that association is not causation. Most importantly, we’ve seen precisely why it isn’t and _**how can we**_ make association be causation. 

It should be:
So far, we’ve seen that association is not causation. Most importantly, we’ve seen precisely why it isn’t and _**how we can**_ make association be causation.

**Comment by matheusfacure** [comment]
Thks for the feedback!
